name: Update pre-commit hooks

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  FORCE_COLOR: 1

jobs:
  auto-update:
    name: Update pre-commit hooks
#    if: ${{ github.repository == 'vacanza/holidays' }}
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Install uv
        uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba
        with:
          python-version: '3.14'
          version: '0.9.9'

      - name: Run pre-commit automatic update
        run: |
          uv tool run pre-commit autoupdate
          uv tool run pre-commit run --all-files

#      - uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e
#        with:
#          base: dev
#          body: Update pre-commit hooks to their latest versions.
#          branch: update-pre-commit-hooks
#          commit-message: 'chore: Update pre-commit hooks'
#          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
#          delete-branch: true
#          title: Update pre-commit hooks
#          token: ${{ github.token }}
